# Generated by Django 5.0.6 on 2024-05-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_usuario_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='mail',
            field=models.CharField(default='Mail', max_length=200),
            preserve_default=False,
        ),
    ]
