# Generated by Django 5.0.6 on 2024-05-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_post_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Titulo', max_length=200),
            preserve_default=False,
        ),
    ]
